import Banner from "@/components/Banner";
import Header from "@/components/Header";
import { token } from "@/sanity/lib/fetch";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { draftMode } from "next/headers";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PreviewProvider = dynamic(() => import("@/components/PreviewProvider"));

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <>
          <Header />
          <Banner />
          {draftMode().isEnabled ? (
            <PreviewProvider token={token}>{children}</PreviewProvider>
          ) : (
            <>{children}</>
          )}
        </>
      </body>
    </html>
  );
}
